name: Infrastructure - AKS + ACR + Kubernetes

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: "true"
  ARM_USE_AZUREAD: "true"
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  

jobs:

  infrastructure:
    name: Terraform Infra - Azure + AKS + ACR
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/infraAKS

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Setup
        uses: ./.github/actions/azure-setup

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve


  kubernetes:
    name: Terraform Kubernetes - NGINX 
    runs-on: ubuntu-latest

    needs:
      - infrastructure

    defaults:
      run:
        working-directory: terraform/k8s

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Setup
        uses: ./.github/actions/azure-setup

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve


  argocd-application:
    name: Terraform - Argo CD Application
    runs-on: ubuntu-latest

    needs:
      - kubernetes
      
    env:
      TF_VAR_argocd_repo_password: ${{ secrets.ARGOCD_REPO_PASSWORD }}

    defaults:
      run:
        working-directory: terraform/argocd-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Setup
        uses: ./.github/actions/azure-setup

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group rg-aks-cuestionario \
            --name aks-cuestionario \
            --overwrite-existing

      - name: Wait for Argo CD Application CRD
        shell: bash
        run: |
          echo "Esperando al CRD applications.argoproj.io..."

          for i in $(seq 1 60); do
            if kubectl get crd applications.argoproj.io >/dev/null 2>&1; then
              echo "CRD Application disponible."
              exit 0
            fi

            sleep 10
          done

          echo "ERROR: el CRD no apareció en 10 minutos."
          exit 1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve