name: Infrastructure - Destroy AKS + ACR

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Escribe DESTROY para confirmar"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: "true"
  ARM_USE_AZUREAD: "true"
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  destroy:
    name: Check Terraform
    runs-on: ubuntu-latest

    steps:

      - name: Validate confirmation
        run: |
          if [ "${{ inputs.confirmation }}" != "DESTROY" ]; then
            echo "ERROR: Debes escribir exactamente DESTROY."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check repository
        run: |
          echo "=== COMMIT ==="
          git rev-parse HEAD

          echo ""
          echo "=== BRANCH ==="
          git branch --show-current

          echo ""
          echo "=== ROOT ==="
          pwd
          ls -la

          echo ""
          echo "=== FILES ==="
          find . -maxdepth 3 -type f | sort

          echo ""
          echo "=== TERRAFORM FILES ==="
          find . -name "*.tf" -print